# Generated by Django 6.0.3 on 2026-03-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Resume created'), ('updated', 'Resume updated'), ('pdf_generated', 'PDF generated'), ('downloaded', 'Downloaded'), ('shared_email', 'Shared via Email'), ('shared_whatsapp', 'Shared via WhatsApp')], max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='resumes.resume')),
            ],
        ),
    ]
